# Generated by Django 6.0.2 on 2026-02-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('active_ingredient', models.CharField(help_text='Componente activo del medicamento', max_length=200)),
                ('concentration', models.CharField(help_text='Ej: 500mg', max_length=100)),
                ('presentation', models.CharField(help_text='Ej: Tableta, Cápsula, Inyectable', max_length=100)),
                ('laboratory', models.CharField(max_length=200)),
                ('registration_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('minimum_stock', models.IntegerField(default=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacture_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('OUT_OF_STOCK', 'Agotado'), ('DISCONTINUED', 'Descontinuado')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='medicines_m_name_61a774_idx'), models.Index(fields=['registration_number'], name='medicines_m_registr_45d213_idx'), models.Index(fields=['is_active'], name='medicines_m_is_acti_e1c701_idx')],
            },
        ),
    ]
