# Generated by Django 6.0.2 on 2026-03-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='medicine',
            name='administration_route',
            field=models.CharField(choices=[('BUCAL', 'Bucal'), ('CUTANEA', 'Cutánea'), ('INHALATORIA', 'Inhalatoria'), ('INTRADERMICA', 'Intradérmica'), ('INTRAMUSCULAR', 'Intramuscular'), ('INTRAVENOSA', 'Intravenosa'), ('NASAL', 'Nasal'), ('OFTALMOLOGICA', 'Oftálmica'), ('ORAL', 'Oral'), ('OTICA', 'Ótica'), ('RECTAL', 'Rectal'), ('SUBCUTANEA', 'Subcutánea'), ('SUBLINGUAL', 'Sublingual'), ('TRANSDERMICA', 'Transdérmica'), ('URETRAL', 'Uretral'), ('VAGINAL', 'Vaginal')], default='ORAL', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='batch_number',
            field=models.CharField(db_index=True, default='BATCH-001', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pharmaceutical_form',
            field=models.CharField(choices=[('ESPECIAL', 'Especial'), ('LIQUIDA', 'Líquida'), ('GASEOSA', 'Gaseosa'), ('SEMISÓLIDA', 'Semisólida'), ('SOLIDA', 'Sólida')], default='SOLIDA', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicine',
            name='requires_formula',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicine',
            name='supplier',
            field=models.CharField(default='Por Definir', max_length=200),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='laboratory',
            field=models.CharField(choices=[('ABBOTT', 'Abbott Laboratories de Colombia S.A.'), ('ANDROMACO', 'Andromaco'), ('BAGO', 'Bagó'), ('BAYER', 'Bayer S.A.'), ('BLASKOV', 'Blaskov S.A.'), ('BOEHRINGER', 'Boehringer Ingelheim Ltda.'), ('COLPHARMA', 'Colpharma S.A.'), ('DISANFAR', 'Disanfar S.A.'), ('ELI_LILLY', 'Eli Lilly Interamérica Inc.'), ('FARMA_COLOMBIA', 'Farma de Colombia S.A.S.'), ('GENFAR', 'Genfar S.A.'), ('GSK', 'GlaxoSmithKline (GSK)'), ('GRUNENTHAL', 'Grünenthal de Colombia S.A.'), ('JOHNSON', 'Johnson & Johnson de Colombia S.A.'), ('LAFRANCOL', 'Lafrancol S.A.S.'), ('LAPROFF', 'Laproff S.A.'), ('LA_SANTE', 'La Santé S.A.'), ('MERCK', 'Merck Sharp & Dohme (MSD)'), ('MK', 'MK'), ('NOVARTIS', 'Novartis de Colombia S.A.'), ('PFIZER', 'Pfizer Ltda.'), ('PROCAPS', 'ProCaps S.A.S.'), ('ROCHE', 'Roche S.A.'), ('ROPSOHN', 'Ropsohn Therapeutics S.A.'), ('SANOFI', 'Sanofi Aventis de Colombia S.A.'), ('SERVIER', 'Servier de Colombia Ltda.'), ('SYNTHESIS', 'Synthesis S.A.'), ('TECNOQUIMICAS', 'Tecnoquímicas S.A. (TQ)')], default='ABBOTT', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='presentation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='state',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('VENCIDO', 'Vencido'), ('AGOTADO', 'Agotado'), ('SUSPENDIDO', 'Suspendido')], db_index=True, default='ACTIVO', max_length=20),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['batch_number'], name='medicines_m_batch_n_31f5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['state'], name='medicines_m_state_3a5e42_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['expiration_date'], name='medicines_m_expirat_8661a0_idx'),
        ),
    ]
