# Generated by Django 6.0.2 on 2026-03-18 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMedicamento',
            fields=[
                ('id', models.AutoField(db_column='id_estado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre_estado', max_length=30, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado de medicamento',
                'verbose_name_plural': 'Estados de medicamentos',
                'db_table': 'estados_medicamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FormaFarmaceutica',
            fields=[
                ('id', models.AutoField(db_column='id_forma', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre_forma', max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Forma farmacéutica',
                'verbose_name_plural': 'Formas farmacéuticas',
                'db_table': 'formas_farmaceuticas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(db_column='id_laboratorio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre_laboratorio', max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
                'db_table': 'laboratorios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ViaAdministracion',
            fields=[
                ('id', models.AutoField(db_column='id_via_administracion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre_via', max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vía de administración',
                'verbose_name_plural': 'Vías de administración',
                'db_table': 'via_administracion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(db_column='id_medicamento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('concentracion', models.CharField(blank=True, max_length=50, null=True)),
                ('laboratorio_texto', models.CharField(blank=True, db_column='laboratorio', max_length=100, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('stock', models.PositiveSmallIntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requiere_formula', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(db_column='creado_por_id', on_delete=django.db.models.deletion.PROTECT, related_name='medicamentos_creados', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, to='products.estadomedicamento')),
                ('forma', models.ForeignKey(db_column='id_forma', on_delete=django.db.models.deletion.PROTECT, to='products.formafarmaceutica')),
                ('laboratorio', models.ForeignKey(db_column='id_laboratorio', on_delete=django.db.models.deletion.PROTECT, related_name='medicamentos_rel', to='products.laboratorio')),
                ('responsable', models.ForeignKey(blank=True, db_column='responsable_id', limit_choices_to={'rol': 'Farmaceuta'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicamentos_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'db_table': 'medicamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MedicamentoHistorial',
            fields=[
                ('id', models.AutoField(db_column='id_historial', primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('CREADO', 'CREADO'), ('ACTUALIZADO', 'ACTUALIZADO'), ('DESHABILITADO', 'DESHABILITADO'), ('CAMBIO_ESTADO', 'CAMBIO_ESTADO')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('medicamento', models.ForeignKey(db_column='id_medicamento', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='products.medicamento')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de medicamento',
                'verbose_name_plural': 'Historial de medicamentos',
                'db_table': 'medicamento_historial',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(db_column='id_presentacion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre_presentacion', max_length=60)),
                ('activo', models.BooleanField(default=True)),
                ('forma', models.ForeignKey(db_column='id_forma', on_delete=django.db.models.deletion.PROTECT, related_name='presentaciones', to='products.formafarmaceutica')),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
                'db_table': 'presentacion',
                'ordering': ['nombre'],
                'unique_together': {('forma', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='medicamento',
            name='presentacion',
            field=models.ForeignKey(db_column='id_presentacion', on_delete=django.db.models.deletion.PROTECT, to='products.presentacion'),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('nit', models.CharField(db_column='nit_proveedor', max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('razon_social', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_contacto', models.EmailField(blank=True, db_column='correo', max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='medicamento',
            name='proveedor',
            field=models.ForeignKey(db_column='nit_proveedor', on_delete=django.db.models.deletion.PROTECT, to='products.proveedor'),
        ),
        migrations.CreateModel(
            name='ProveedorHistorial',
            fields=[
                ('id', models.AutoField(db_column='id_historial', primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('CREADO', 'CREADO'), ('ACTUALIZADO', 'ACTUALIZADO'), ('CAMBIO_ESTADO', 'CAMBIO_ESTADO')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(db_column='nit_proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='products.proveedor')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de proveedor',
                'verbose_name_plural': 'Historial de proveedores',
                'db_table': 'proveedor_historial',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='medicamento',
            name='via_administracion',
            field=models.ForeignKey(db_column='id_via_administracion', on_delete=django.db.models.deletion.PROTECT, to='products.viaadministracion'),
        ),
    ]
