# Generated by Django 6.0.2 on 2026-02-28 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormaFarmaceutica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViaAdministracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('concentracion', models.CharField(max_length=120)),
                ('lote', models.CharField(max_length=60)),
                ('fecha_fabricacion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('stock', models.PositiveSmallIntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requiere_formula', models.BooleanField(default=False)),
                ('descripcion', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicamentos_creados', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.estadomedicamento')),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.formafarmaceutica')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.laboratorio')),
                ('responsable', models.ForeignKey(blank=True, limit_choices_to={'rol': 'Farmaceuta'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicamentos_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREADO', 'CREADO'), ('ACTUALIZADO', 'ACTUALIZADO'), ('DESHABILITADO', 'DESHABILITADO')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='products.medicamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('activo', models.BooleanField(default=True)),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentaciones', to='products.formafarmaceutica')),
            ],
            options={
                'unique_together': {('forma', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='medicamento',
            name='presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.presentacion'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.proveedor'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='via_administracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.viaadministracion'),
        ),
    ]
