# Generated by Django 6.0.2 on 2026-04-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='medicamentos/'),
        ),
    ]
