# Generated by Django 6.0.2 on 2026-03-14 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_proveedor_completo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentohistorial',
            name='accion',
            field=models.CharField(choices=[('CREADO', 'CREADO'), ('ACTUALIZADO', 'ACTUALIZADO'), ('DESHABILITADO', 'DESHABILITADO'), ('CAMBIO_ESTADO', 'CAMBIO_ESTADO')], max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='ProveedorHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREADO', 'CREADO'), ('ACTUALIZADO', 'ACTUALIZADO'), ('CAMBIO_ESTADO', 'CAMBIO_ESTADO')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='products.proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
