# Generated by Django 6.0.2 on 2026-03-21 01:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True, verbose_name='Número de factura')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de la venta')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tipo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta débito', 'Tarjeta débito'), ('Tarjeta crédito', 'Tarjeta crédito'), ('Transferencia', 'Transferencia')], max_length=30, verbose_name='Tipo de pago')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de confirmación'), ('Completada', 'Completada'), ('Anulada', 'Anulada')], default='Pendiente', max_length=20, verbose_name='Estado de la venta')),
                ('confirmacion_vendedor_en', models.DateTimeField(blank=True, null=True, verbose_name='Confirmación de pago (vendedor)')),
                ('confirmacion_cliente_en', models.DateTimeField(blank=True, null=True, verbose_name='Confirmación de pago (cliente)')),
                ('cliente', models.ForeignKey(limit_choices_to={'rol': 'Cliente'}, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_como_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('confirmacion_cliente_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('confirmacion_vendedor_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(limit_choices_to={'rol__in': ['Administrador', 'Farmaceuta']}, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realiza la venta')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='VentaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('detalle', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='sales.venta')),
            ],
            options={
                'verbose_name': 'Historial de venta',
                'verbose_name_plural': 'Historial de ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='VentaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio unitario (venta)')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_venta', to='products.medicamento')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='sales.venta')),
            ],
            options={
                'verbose_name': 'Línea de venta',
                'verbose_name_plural': 'Líneas de venta',
            },
        ),
    ]
