# Generated by Django 6.0.2 on 2026-04-07 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={},
        ),
        migrations.AddField(
            model_name='venta',
            name='ciudad_entrega',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Ciudad de entrega'),
        ),
        migrations.AddField(
            model_name='venta',
            name='direccion_entrega',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección de entrega'),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_entrega',
            field=models.CharField(blank=True, choices=[('delivery', 'Domicilio'), ('pickup', 'Recogida en tienda')], max_length=20, null=True, verbose_name='Método de entrega'),
        ),
        migrations.AddField(
            model_name='venta',
            name='nombre_contacto_retiro',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nombre de contacto para retiro'),
        ),
        migrations.AddField(
            model_name='venta',
            name='punto_retiro',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Punto de retiro'),
        ),
        migrations.AddField(
            model_name='venta',
            name='telefono_contacto_retiro',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono de contacto para retiro'),
        ),
        migrations.AddField(
            model_name='venta',
            name='telefono_entrega',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono de entrega'),
        ),
        migrations.CreateModel(
            name='NotificacionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENTA_WEB_PENDIENTE', 'Venta web pendiente'), ('VENTA_APROBADA', 'Venta aprobada'), ('VENTA_ANULADA', 'Venta anulada'), ('CARRITO_ACTIVO', 'Carrito activo'), ('GENERAL', 'General')], default='GENERAL', max_length=40, verbose_name='Tipo de notificación')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('leida_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_ventas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario destinatario')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='sales.venta', verbose_name='Venta asociada')),
            ],
            options={
                'ordering': ('-creada_en',),
            },
        ),
    ]
