# Generated by Django 6.0.2 on 2026-04-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_venta_options_venta_ciudad_entrega_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ('-fecha_hora',), 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
